[
  {
    name: 'Yellow Tulip Bouquet',
    price: 30,
    quantity: 15,
    bloomdate: '2024-02-05',
    discount: 'false',
    type: 'tulip',
    fragrance: 'soft',
    colors: ['yellow', 'white'],
    sizes: ['small', 'medium'],
    arrangementStyles: ['bouquet', 'vase'],
    occasions: ['birthday', 'anniversary', 'wedding'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Blue Orchid Vase',
    price: 40,
    quantity: 10,
    bloomdate: '2024-02-12',
    discount: 'true',
    type: 'orchid',
    fragrance: 'strong',
    colors: ['blue', 'purple'],
    sizes: ['large'],
    arrangementStyles: ['vase'],
    occasions: ['wedding', 'anniversary'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'White Lily Basket',
    price: 35,
    quantity: 18,
    bloomdate: '2024-02-18',
    discount: 'false',
    type: 'lily',
    fragrance: 'soft',
    colors: ['white', 'pink'],
    sizes: ['medium'],
    arrangementStyles: ['basket'],
    occasions: ['anniversary', 'wedding'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Black Rose Single',
    price: 28,
    quantity: 20,
    bloomdate: '2024-02-25',
    discount: 'false',
    type: 'rose',
    fragrance: 'strong',
    colors: ['black', 'red'],
    sizes: ['small'],
    arrangementStyles: ['single', 'vase'],
    occasions: ['birthday'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Red Dahlia Bouquet',
    price: 32,
    quantity: 14,
    bloomdate: '2024-03-03',
    discount: 'true',
    type: 'dahlia',
    fragrance: 'sweet',
    colors: ['red', 'orange'],
    sizes: ['large', 'medium'],
    arrangementStyles: ['bouquet'],
    occasions: ['wedding', 'birthday'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Lavender Lily Vase',
    price: 38,
    quantity: 16,
    bloomdate: '2024-03-10',
    discount: 'false',
    type: 'lily',
    fragrance: 'soft',
    colors: ['lavender', 'white'],
    sizes: ['medium'],
    arrangementStyles: ['vase'],
    occasions: ['anniversary', 'wedding'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Yellow Tulip Single',
    price: 22,
    quantity: 22,
    bloomdate: '2024-03-17',
    discount: 'false',
    type: 'tulip',
    fragrance: 'soft',
    colors: ['yellow', 'white'],
    sizes: ['small'],
    arrangementStyles: ['single'],
    occasions: ['birthday'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Blue Orchid Bouquet',
    price: 42,
    quantity: 12,
    bloomdate: '2024-03-24',
    discount: 'true',
    type: 'orchid',
    fragrance: 'strong',
    colors: ['blue', 'purple'],
    sizes: ['medium', 'large'],
    arrangementStyles: ['bouquet'],
    occasions: ['wedding', 'anniversary'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'White Lily Single',
    price: 30,
    quantity: 18,
    bloomdate: '2024-03-31',
    discount: 'false',
    type: 'lily',
    fragrance: 'soft',
    colors: ['white', 'pink'],
    sizes: ['small'],
    arrangementStyles: ['single'],
    occasions: ['anniversary', 'wedding'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Purple Daisy Basket',
    price: 33,
    quantity: 15,
    bloomdate: '2024-04-07',
    discount: 'true',
    type: 'daisy',
    fragrance: 'sweet',
    colors: ['purple', 'white'],
    sizes: ['medium'],
    arrangementStyles: ['basket'],
    occasions: ['birthday', 'wedding'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Sunflower Vase',
    price: 45,
    quantity: 12,
    bloomdate: '2024-04-14',
    discount: 'false',
    type: 'sunflower',
    fragrance: 'strong',
    colors: ['yellow'],
    sizes: ['large'],
    arrangementStyles: ['vase'],
    occasions: ['anniversary'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Red Rose Single',
    price: 28,
    quantity: 20,
    bloomdate: '2024-04-21',
    discount: 'true',
    type: 'rose',
    fragrance: 'strong',
    colors: ['red', 'white'],
    sizes: ['small'],
    arrangementStyles: ['single'],
    occasions: ['birthday'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Pink Carnation Bouquet',
    price: 27,
    quantity: 18,
    bloomdate: '2024-04-28',
    discount: 'false',
    type: 'carnation',
    fragrance: 'soft',
    colors: ['pink', 'red'],
    sizes: ['large', 'medium'],
    arrangementStyles: ['bouquet'],
    occasions: ['wedding', 'anniversary'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Orange Dahlia Vase',
    price: 34,
    quantity: 14,
    bloomdate: '2024-05-05',
    discount: 'true',
    type: 'dahlia',
    fragrance: 'none',
    colors: ['orange', 'yellow'],
    sizes: ['large', 'medium'],
    arrangementStyles: ['vase'],
    occasions: ['wedding', 'birthday'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Yellow Rose Basket',
    price: 37,
    quantity: 16,
    bloomdate: '2024-05-12',
    discount: 'false',
    type: 'rose',
    fragrance: 'strong',
    colors: ['yellow', 'white'],
    sizes: ['medium', 'small'],
    arrangementStyles: ['basket'],
    occasions: ['anniversary', 'wedding'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'White Orchid Single',
    price: 31,
    quantity: 20,
    bloomdate: '2024-05-19',
    discount: 'false',
    type: 'orchid',
    fragrance: 'soft',
    colors: ['white', 'purple'],
    sizes: ['small'],
    arrangementStyles: ['single'],
    occasions: ['anniversary', 'wedding'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
  {
    name: 'Blue Lily Bouquet',
    price: 36,
    quantity: 18,
    bloomdate: '2024-05-26',
    discount: 'true',
    type: 'lily',
    fragrance: 'soft',
    colors: ['blue', 'white'],
    sizes: ['medium', 'large'],
    arrangementStyles: ['bouquet'],
    occasions: ['anniversary', 'wedding'],
    createdBy: {
      $oid: '65b39c235fd07f984afabb0f',
    },
    creatorsEmail: 'xpawal@gmail.com',
  },
];
